import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const read = (path) => readFileSync(join(root, path), "utf8");

const constants = read("src/lib/constants.ts");
const schema = read("supabase/schema.sql");
const migration = read("supabase/migrations/20260609120000_beta_hardening.sql");
const tarkovQuestMigration = read("supabase/migrations/20260609130000_tarkov_profiles_quest_help.sql");
const spokenLanguagesMigration = read("supabase/migrations/20260609150000_spoken_languages_compatibility.sql");
const betaSecurityMigration = read("supabase/migrations/20260610100000_beta_security_public_data.sql");
const compatibilityV2Migration = read("supabase/migrations/20260611100000_compatibility_v2.sql");
const betaHardeningMigration = read("supabase/migrations/20260611110000_beta_hardening.sql");
const finalHardeningMigration = read("supabase/migrations/20260611123000_final_beta_hardening.sql");
const p0HardeningMigration = read("supabase/migrations/20260612010000_p0_beta_hardening.sql");
const archiveDataApiGrantsMigration = read("supabase/migrations/20260722101011_archive_data_api_grants.sql");
const v11Migration = read("supabase/migrations/20260925100000_v1_1_fixes_responses_game_modes.sql");
const demoMode = read("src/lib/demo/mode.ts");
const middleware = read("src/proxy.ts");
const postResponsesAction = read("src/lib/actions/post-responses.ts");
const envExample = read(".env.example");
const gitignore = read(".gitignore");
const swipeAction = read("src/lib/actions/swipe.ts");
const chatAction = read("src/lib/actions/chat.ts");
const chatPanel = read("src/components/app/chat-panel.tsx");
const raidAction = read("src/lib/actions/raid-now.ts");
const moderationAction = read("src/lib/actions/moderation.ts");
const swipePage = read("src/app/(app)/swipe/page.tsx");
const swipeDeck = read("src/components/app/swipe-deck.tsx");
const questForm = read("src/components/app/quest-help-form.tsx");
const raidBoard = read("src/components/app/raid-now-board.tsx");
const questBoard = read("src/components/app/quest-help-board.tsx");
const onboardingForm = read("src/components/app/onboarding-form.tsx");
const settingsPanel = read("src/components/app/settings-panel.tsx");
const profileComponents = read("src/components/app/player-profile.tsx");
const tarkovClient = read("src/lib/tarkov/client.ts");
const tarkovAction = read("src/lib/actions/tarkov.ts");
const questAction = read("src/lib/actions/quest-help.ts");
const moderationText = read("src/lib/moderation/text.ts");
const appShell = read("src/components/app/app-shell.tsx");
const appNav = read("src/components/app/app-nav.tsx");
const protectedLayout = read("src/app/(app)/layout.tsx");
const rootLayout = read("src/app/layout.tsx");
const manifest = read("public/manifest.webmanifest");
const serviceWorker = read("public/sw.js");
const globals = read("src/app/globals.css");
const queries = read("src/lib/supabase/queries.ts");
const onboardingAction = read("src/lib/actions/profile.ts");
const authCallback = read("src/app/auth/callback/route.ts");
const rateLimit = read("src/lib/rate-limit.ts");
const oauthOrigin = read("src/lib/oauth-origin.ts");
const nextConfig = read("next.config.ts");
const packageJson = read("package.json");
const avatarStorage = read("src/lib/avatar-storage.ts");
const adminPage = read("src/app/(app)/admin/reports/page.tsx");
const adminAction = read("src/lib/actions/admin.ts");
const privacyPage = read("src/app/privacy/page.tsx");
const termsPage = read("src/app/terms/page.tsx");
const raidPage = read("src/app/(app)/raid-now/page.tsx");
const questPage = read("src/app/(app)/quest-help/page.tsx");

assert.match(constants, /"Icebreaker"/, "MAPS must include Icebreaker");
assert.match(constants, /"IT"/, "LANGUAGES must include IT");
assert.match(constants, /"Streets of Tarkov"/, "MAPS must include Streets of Tarkov");
assert.match(constants, /"The Labyrinth"/, "MAPS must include The Labyrinth");
assert.match(constants, /MAP_ALIASES/, "map aliases must be defined");
assert.match(schema, /'Icebreaker'/, "schema eft_map enum must include Icebreaker");
assert.match(migration, /alter type public\.eft_map add value if not exists 'Icebreaker'/, "migration must add Icebreaker safely");
assert.match(tarkovQuestMigration, /profile_tarkov_stats/, "migration must add profile_tarkov_stats");
assert.match(tarkovQuestMigration, /quest_help_posts/, "migration must add quest_help_posts");
assert.match(tarkovQuestMigration, /profile_reviews/, "migration must prepare profile_reviews");
assert.match(spokenLanguagesMigration, /alter type public\.language_code add value if not exists 'IT'/, "migration must add IT safely");
assert.match(spokenLanguagesMigration, /spoken_languages public\.language_code\[\]/, "migration must add spoken_languages");
assert.match(spokenLanguagesMigration, /compatibility_reasons text\[\]/, "RPC must return compatibility reasons");
assert.match(compatibilityV2Migration, /compatibility_warnings text\[\]/, "Compatibility V2 must return warnings");
assert.match(compatibilityV2Migration, /shared_languages public\.language_code\[\]/, "Compatibility V2 must return shared languages");
assert.match(compatibilityV2Migration, /shared_maps public\.eft_map\[\]/, "Compatibility V2 must return shared maps");
assert.match(compatibilityV2Migration, /shared_objectives public\.raid_objective\[\]/, "Compatibility V2 must return shared objectives");
assert.match(compatibilityV2Migration, /shared_styles public\.play_style\[\]/, "Compatibility V2 must return shared styles");
assert.match(compatibilityV2Migration, /profile_tarkov_stats stats/, "Compatibility V2 must use saved Tarkov stats");
assert.match(compatibilityV2Migration, /case when not points\.has_shared_language then 55/, "Compatibility V2 must cap no-language matches");
assert.match(compatibilityV2Migration, /case when not points\.has_shared_schedule then 70/, "Compatibility V2 must cap no-schedule matches");
assert.match(compatibilityV2Migration, /player_preferences/, "Compatibility V2 must use player preferences");
assert.match(betaHardeningMigration, /create table if not exists public\.rate_limit_buckets/, "beta hardening must add persistent rate limit buckets");
assert.match(betaHardeningMigration, /create or replace function public\.check_rate_limit/, "beta hardening must add persistent rate limit RPC");
assert.match(betaHardeningMigration, /delete from public\.rate_limit_buckets/, "rate limit RPC must clean old buckets");
assert.match(betaHardeningMigration, /position\(auth\.uid\(\)::text in p_key\) = 0/, "rate limit RPC must reject keys for other users");
assert.match(finalHardeningMigration, /char_length\(p_key\) > 140/, "final rate limit RPC must cap key length");
assert.match(finalHardeningMigration, /p_limit <> v_limit/, "final rate limit RPC must reject manipulated limits");
assert.match(finalHardeningMigration, /p_window_seconds <> v_window_seconds/, "final rate limit RPC must reject manipulated windows");
assert.doesNotMatch(finalHardeningMigration, /position\(auth\.uid\(\)::text in p_key\) = 0/, "final rate limit RPC must not use substring uid matching");
assert.match(betaHardeningMigration, /create table if not exists public\.user_roles/, "beta hardening must add admin roles table");
assert.match(betaHardeningMigration, /create or replace function public\.is_admin/, "beta hardening must add admin role RPC");
assert.match(betaHardeningMigration, /Admins see reports/, "admins must have report select policy");
assert.match(betaHardeningMigration, /Admins update reports/, "admins must have report update policy");
assert.doesNotMatch(betaHardeningMigration, /add column if not exists admin_note/, "report moderation notes must not live on reporter-readable reports");
assert.doesNotMatch(betaHardeningMigration, /add column if not exists reviewed_by/, "report reviewer identity must not live on reporter-readable reports");
assert.match(betaHardeningMigration, /create table if not exists public\.match_reads/, "badges must track read matches");
assert.match(betaHardeningMigration, /create or replace function public\.get_app_badges/, "badges must use server RPC");
assert.match(betaHardeningMigration, /post\.status = 'Activa'/, "Quest Help responses must be limited to active posts");
assert.match(betaHardeningMigration, /public\.check_rate_limit\('db:swipe:'/, "create_swipe RPC must enforce direct-call rate limiting");
assert.match(betaHardeningMigration, /public\.check_rate_limit\('db:message:'/, "messages RLS must rate limit direct inserts");
assert.match(betaHardeningMigration, /public\.check_rate_limit\('db:raid-now:create:'/, "Raid Now RLS must rate limit direct inserts");
assert.match(betaHardeningMigration, /public\.check_rate_limit\('db:quest-help:create:'/, "Quest Help RLS must rate limit direct inserts");
assert.match(betaHardeningMigration, /public\.check_rate_limit\('db:report:'/, "reports RLS must rate limit direct inserts");
assert.match(betaHardeningMigration, /public\.check_rate_limit\('db:block:'/, "blocks RLS must rate limit direct inserts");
assert.match(schema, /spoken_languages public\.language_code\[\] not null default '\{\}'/, "schema must include spoken_languages");
assert.match(schema, /create unlogged table public\.rate_limit_buckets/, "schema must include persistent rate limit buckets for clean installs");
assert.match(schema, /create table public\.user_roles/, "schema must include admin roles for clean installs");
assert.match(schema, /create table public\.match_reads/, "schema must include match read tracking for clean installs");
assert.match(schema, /create or replace function public\.check_rate_limit/, "schema must include rate limit RPC for clean installs");
assert.match(schema, /create or replace function public\.is_admin/, "schema must include admin RPC for clean installs");
assert.match(schema, /create or replace function public\.get_app_badges/, "schema must include app badges RPC for clean installs");
assert.match(betaSecurityMigration, /drop column if exists discord_username/, "migration must remove public Discord username column");
assert.match(betaSecurityMigration, /drop column if exists discord_id/, "migration must remove public Discord id column");
assert.match(betaSecurityMigration, /get_public_tarkov_stats/, "migration must expose limited public Tarkov stats through RPC");
assert.match(betaSecurityMigration, /revoke select, insert, update on public\.profiles from authenticated/, "profiles table must use column-level grants");
const profileSelectGrant = betaSecurityMigration.match(/grant select \(([\s\S]*?)\) on public\.profiles to authenticated/)?.[1] ?? "";
const profileUpdateGrant = betaSecurityMigration.match(/grant update \(([\s\S]*?)\) on public\.profiles to authenticated/)?.[1] ?? "";
assert.doesNotMatch(profileSelectGrant, /discord_|premium_/, "profile select grants must not include Discord or premium fields");
assert.doesNotMatch(profileUpdateGrant, /discord_|premium_|is_premium/, "profile update grants must not include protected fields");
assert.match(schema, /public_profiles_view/, "schema must include public profile view without Discord");
assert.match(schema, /Users see own tarkov stats/, "direct Tarkov stats table reads must be owner-only");
assert.match(schema, /grant select \([\s\S]*on public\.profiles to authenticated/, "schema must grant only explicit profile columns");
assert.match(archiveDataApiGrantsMigration, /from anon;/, "Data API migration must keep anonymous table access disabled");
assert.match(archiveDataApiGrantsMigration, /public\.messages to authenticated/, "Data API migration must grant authenticated message access for RLS to evaluate");
assert.match(archiveDataApiGrantsMigration, /public\.user_roles, public\.rate_limit_buckets from authenticated/, "private internal tables must remain unavailable to authenticated clients");
assert.match(archiveDataApiGrantsMigration, /to service_role;/, "RLS test and administrative clients need explicit service role table grants");

assert.match(gitignore, /^\.env\.local$/m, ".env.local must be ignored");
assert.doesNotMatch(envExample, /sb_(?:secret|publishable)_[A-Za-z0-9_-]{20,}/, ".env.example must not contain real Supabase keys");
assert.doesNotMatch(envExample, /eyJ[A-Za-z0-9_-]{30,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/, ".env.example must not contain legacy Supabase JWT keys");
assert.doesNotMatch(envExample, /NEXT_PUBLIC_DEMO_MODE/, "fake swipe profiles must not be mixed into a real backend");
assert.match(demoMode, /DEMO_PRODUCTION_BUILD === "true" && !hosted/, "a production build may only run the demo with an explicit second flag");
assert.match(demoMode, /process\.env\.NETLIFY \|\| process\.env\.VERCEL/, "hosted environments must never run the in-memory demo");
assert.match(middleware, /isDemoBackend\(\)/, "middleware must isolate demo sessions");
assert.ok(!existsSync(join(root, "middleware.ts")), "the proxy must live in src/ (a root file is ignored when using src/, so Supabase sessions were never refreshed)");
assert.match(middleware, /updateSession\(request\)/, "middleware must refresh Supabase sessions");
assert.doesNotMatch(swipePage, /withDemoProfiles|isDemoModeEnabled/, "swipe must only show real candidates");
assert.doesNotMatch(swipeDeck, /profile\.discord_username/, "swipe card must not render Discord username");
assert.match(swipeDeck, /PlayerProfileModal/, "swipe cards must open expanded profile modal");
assert.match(queries, /discord_id: null/, "swipe candidates must be sanitized");
assert.doesNotMatch(queries, /select\(\s*["'`]\*/, "queries must not use select star");
assert.doesNotMatch(queries, /profiles\(\*\)|profile:profiles\(\*\)/, "queries must not join full profiles");
assert.match(queries, /PUBLIC_PROFILE_SELECT/, "queries must use explicit public profile columns");
assert.match(queries, /get_public_tarkov_stats/, "public stats must use limited RPC");
assert.doesNotMatch(queries, /messages\(body, created_at\)/, "matches must not load every message through nested relation");
assert.match(onboardingForm, /fields\.spokenLanguages/, "onboarding must collect spoken languages");
assert.match(onboardingForm, /name: "spoken_languages"/, "onboarding must submit spoken_languages");
assert.match(onboardingForm, /options: LANGUAGE_OPTIONS/, "onboarding spoken languages must use shared language options");
assert.match(onboardingForm, /PROFILE_LIMITS/, "onboarding must enforce the same selection limits as the server");
assert.match(settingsPanel, /updateProfileLanguages/, "settings must update profile languages");
assert.match(settingsPanel, /name="spoken_languages"/, "settings must submit spoken_languages");
assert.match(onboardingAction, /new Set\(\[parsed\.data\.language, \.\.\.parsed\.data\.spoken_languages\]\)/, "onboarding must always include primary language in spoken_languages");
assert.match(onboardingAction, /updateProfileLanguages[\s\S]*new Set\(\[parsed\.data\.language, \.\.\.parsed\.data\.spoken_languages\]\)/, "settings must always include primary language in spoken_languages");
assert.match(swipeDeck, /speaksYourLanguage/, "swipe must show same-language badge");
assert.match(swipeDeck, /MatchCelebration/, "a mutual like must open the match dialog with a chat link");
assert.match(swipeDeck, /onTap=/, "dragging a card must not open the profile (onTap instead of onClick)");
assert.match(swipeDeck, /compatibility_reasons/, "swipe must render compatibility reasons");
assert.match(swipeDeck, /activeSwipeId/, "swipe must prevent duplicate submissions");
assert.match(swipeDeck, /disabled=\{swipeLocked\}/, "swipe buttons must disable while sending");
assert.match(profileComponents, /compatibility_warnings/, "expanded profile must render compatibility warnings");
assert.match(profileComponents, /shared_languages/, "expanded profile must render shared languages");
assert.match(profileComponents, /shared_maps/, "expanded profile must render shared maps");
assert.match(schema, /create table public\.profile_contacts/, "Discord contact data must be in a private table");
assert.match(migration, /update public\.profiles\s+set discord_username = null/, "migration must clear public Discord fields");
assert.match(queries, /from\("profile_contacts"\)/, "match details must read contacts from private table");
assert.match(profileComponents, /PlayerProfileStats/, "expanded profile components must exist");
assert.match(profileComponents, /PlayerTarkovStats/, "expanded profile must render Tarkov stats");
assert.match(profileComponents, /PlayerQuestNeeds/, "expanded profile must render quest needs");
assert.match(profileComponents, /spokenLanguages/, "expanded profile must render spoken languages");
assert.match(profileComponents, /matched && profile\.discord_id/, "expanded profile must only build Discord user links for matches");
assert.match(profileComponents, /matched \?/, "expanded profile must gate Discord UI behind matched state");
assert.match(tarkovClient, /https:\/\/api\.tarkov\.dev\/graphql/, "tarkov.dev client must use GraphQL endpoint");
assert.match(tarkovClient, /https:\/\/players\.tarkov\.dev\/profile/, "tarkov client must use public player JSON endpoint");
assert.match(tarkovClient, /TARKOV_CACHE_SECONDS = 5 \* 60/, "player stats must use 5 minute cache");
assert.match(tarkovClient, /info\.experience/, "player stats must derive level from experience");
assert.match(tarkovClient, /\["Sessions", "Pmc"\]/, "player stats must read PMC raids");
assert.match(tarkovClient, /\["ExitStatus", "Survived", "Pmc"\]/, "player stats must read survived raids");
assert.match(tarkovClient, /\["KilledPmc"\]/, "player stats must read PMC kills");
assert.match(tarkovClient, /getTasks/, "tarkov client must expose getTasks");
assert.match(tarkovClient, /getTaskByName/, "tarkov client must expose getTaskByName");
assert.match(tarkovClient, /getPlayerByUrl/, "tarkov client must expose getPlayerByUrl fallback");
assert.match(tarkovClient, /objectives/, "tarkov tasks must include objectives");
assert.match(tarkovClient, /trader/, "tarkov tasks must include trader");
assert.match(tarkovClient, /taskRequirements/, "tarkov tasks must include requirements");
assert.match(tarkovAction, /syncTarkovStats/, "settings must support Tarkov stats sync");
assert.match(tarkovAction, /remoteStats\?\.level/, "Tarkov action must store remote stats when available");
assert.match(settingsPanel, /tarkov\.syncNow/, "settings must expose explicit sync action");
assert.match(settingsPanel, /tarkov\.lastSync/, "settings must show last sync date");
assert.match(settingsPanel, /tarkov\.source/, "settings must show stats source");
assert.match(questAction, /createQuestHelpPost/, "Quest Help creation action must exist");
assert.match(questAction, /containsForbiddenTradeText/, "Quest Help must block RMT/payment language");
assert.match(questAction, /compatibleMaps/, "Quest Help must validate compatible maps server-side");
assert.match(moderationText, /paypal\|bizum/, "Quest Help must block PayPal/Bizum text");
assert.match(moderationText, /rublos\?/, "Quest Help must block ruble payment text in trade context");
assert.match(questForm, /lockedMap/, "Quest Help form must lock single-map quests");
assert.match(questForm, /datalist id="quest-options"/, "Quest Help must include searchable quest selector");
assert.match(questForm, /slice\(0, 80\)/, "Quest Help datalist must be capped");
assert.match(questForm, /const mapValue = lockedMap/, "Quest Help must auto-fill selected quest map");
assert.match(questForm, /uniqueCompatibleMaps\.length > 1/, "Quest Help must allow multiple compatible maps");
assert.match(questForm, /form\.manualFallback/, "Quest Help must show manual fallback warning");
assert.match(appNav, /\/quest-help/, "Quest Help must be navigable");
assert.match(appNav, /\/settings/, "Settings must be navigable");
assert.match(appNav, /fixed bottom-0/, "mobile bottom navigation must exist");
assert.doesNotMatch(appNav, /\sprefetch[\s>]/, "navigation must not force full prefetches of dynamic pages (each one is a full server render with auth and DB queries)");
assert.match(appShell, /ShellStatusProvider/, "AppShell must show internal badges");
assert.doesNotMatch(appShell, /getAppBadges|requireCompletedProfile/, "the layout must not query the database: it re-renders on every prefetch and navigation");
assert.match(read("src/components/app/shell-status.tsx"), /MIN_INTERVAL_MS/, "header badges must be refreshed on a throttle, not per render");
assert.match(appNav, /\/admin\/reports/, "AppShell must include admin nav only for admins");
assert.match(protectedLayout, /AppShell/, "protected sections must share persistent AppShell layout");
assert.match(rootLayout, /manifest: "\/manifest\.webmanifest"/, "root metadata must include PWA manifest");
assert.match(rootLayout, /viewportFit: "cover"/, "viewport must support iOS safe area");
assert.match(manifest, /"display": "standalone"/, "PWA manifest must be installable");
assert.match(manifest, /icon-192\.png/, "PWA manifest must include PNG 192 icon");
assert.match(manifest, /icon-512\.png/, "PWA manifest must include PNG 512 icon");
assert.match(serviceWorker, /self\.addEventListener\("install"/, "service worker must be present");
assert.doesNotMatch(serviceWorker, /request\.destination === "script"|request\.destination === "style"/, "service worker must not cache JS/CSS chunks");
assert.match(globals, /safe-area-inset-bottom|safe-area-inset-left/, "safe-area CSS must be present");

for (const [name, source] of [
  ["swipeProfile", swipeAction],
  ["sendMessage", chatAction],
  ["createRaidNowPost", raidAction],
  ["reportUser/blockUser", moderationAction],
  ["syncTarkovStats", tarkovAction],
  ["createQuestHelpPost", questAction],
]) {
  assert.match(source, /checkPersistentRateLimit/, `${name} must use persistent rate limiting`);
  assert.doesNotMatch(source, /error\.message/, `${name} must not return Supabase error.message`);
}

assert.match(rateLimit, /check_rate_limit/, "rate limit helper must call Supabase RPC");
assert.match(rateLimit, /NODE_ENV !== "production"[\s\S]*checkRateLimit/, "in-memory limiter must only be a non-production fallback");

assert.match(schema, /check_rate_limit\('db:message:' \|\| \(select auth\.uid\(\)\)::text \|\| ':' \|\| match_id::text, 10, 60\)/, "the messages insert policy must enforce 10 messages/minute in the database");
assert.match(chatAction, /loadOlderMessages/, "chat must expose paginated older message loading");
assert.match(chatAction, /checkPersistentRateLimit/, "older message pagination must be rate limited");
assert.match(chatAction, /\.lt\("created_at", parsed\.data\.before\)/, "older chat messages must use cursor pagination");
assert.match(chatAction, /\.limit\(31\)/, "older chat messages must fetch one extra row to detect more pages");
assert.match(chatPanel, /loadOlder/, "chat UI must include load older messages action");
assert.match(raidAction, /\.select\("id", \{ count: "exact", head: true \}\)/, "raid-now must check active post count");
assert.match(raidAction, /rpc\("close_raid_now_post"/, "raid-now close must use scoped RPC");
assert.match(questAction, /rpc\("close_quest_help_post"/, "quest-help close must use scoped RPC");
assert.match(moderationAction, /uuidSchema\.safeParse/, "moderation actions must validate UUIDs");
assert.match(raidAction, /uuidSchema\.safeParse/, "closeRaidNowPost must validate UUID");

assert.match(schema, /can_access_match/, "schema must define can_access_match");
assert.match(schema, /Participants see matches/, "schema must include matches participant RLS");
assert.match(schema, /Participants see messages/, "schema must include messages participant RLS");
assert.match(schema, /Matched users see profile contacts/, "schema must restrict Discord contact access to owner or matches");
assert.match(schema, /touch_match_activity/, "schema must use RPC for match activity updates");
assert.doesNotMatch(schema, /Participants update match activity/, "schema must not expose broad match update policy");

assert.match(queries, /if \(!user\) redirect\("\/login"\)/, "auth guard must redirect anonymous users");
assert.match(queries, /if \(!profile\?\.onboarding_complete\) redirect\("\/onboarding"\)/, "protected pages must require onboarding");
assert.match(queries, /getAppBadges/, "queries must expose internal badges");
assert.match(queries, /getAdminReports/, "queries must expose admin report loader");
assert.match(queries, /from\("match_reads"\)\.upsert/, "opening a match must mark it as read");
assert.match(adminPage, /getAdminReports/, "admin reports page must load reports server-side");
assert.match(adminPage, /notFound\(\)/, "admin reports page must hide from non-admin users");
assert.match(adminAction, /is_admin/, "admin report action must verify admin role server-side");
assert.match(adminAction, /updateReportStatus/, "admin report action must update status");
assert.doesNotMatch(adminAction, /service_role/i, "admin action must not use service role");
assert.match(privacyPage, /legal/, "privacy page must render legal translations");
assert.match(termsPage, /legal/, "terms page must render legal translations");
assert.match(raidBoard, /filters\.apply/, "Raid Now must expose basic filters");
assert.match(questBoard, /filters\.apply/, "Quest Help must expose basic filters");
assert.match(raidPage, /resolveRaidNowErrorCode/, "Raid Now must map technical errors to codes");
assert.match(questPage, /resolveQuestHelpErrorCode/, "Quest Help must map technical errors to codes");
assert.match(onboardingAction, /redirect\(onboardingErrorRedirectPath\("action\.generic"\)\)/, "onboarding must keep production errors generic");
assert.match(onboardingAction, /ONBOARDING_ERROR/, "onboarding must log detailed server-side errors in development");
assert.match(onboardingAction, /checkPersistentRateLimit/, "profile writes must use persistent rate limiting");
assert.doesNotMatch(onboardingAction, /\.\.\.profileData/, "onboarding must not spread Discord into profiles");
const profilePayloadBlock = onboardingAction.match(/const profilePayload = \{([\s\S]*?)\n  \};/)?.[1] ?? "";
assert.doesNotMatch(profilePayloadBlock, /discord_username|discord_id/, "profiles payload must not contain Discord fields");
assert.match(tarkovAction, /optionalUrl/, "Tarkov stats URL must be optional for manual stats");
assert.match(authCallback, /safeNextPath/, "auth callback must sanitize next redirects");
assert.doesNotMatch(authCallback, /requestUrl\.searchParams\.get\("next"\) \?\?/, "auth callback must not trust raw next param");
assert.doesNotMatch(authCallback, /new URL\(next, requestUrl\.origin\)/, "auth callback must not redirect to unvalidated request origin");
assert.match(oauthOrigin, /OAUTH_ALLOWED_ORIGINS/, "OAuth origins must be allowlisted");
assert.match(rateLimit, /return checkRateLimit\(options\)/, "rate limit helper must only use memory fallback explicitly");
assert.match(rateLimit, /ok: false/, "rate limit helper must fail closed");
assert.doesNotMatch(rateLimit, /ok: true,[\s\S]*remaining: options\.limit/, "rate limit helper must not fail open after RPC errors");
assert.match(p0HardeningMigration, /drop policy if exists "Users update own raid posts"/, "P0 migration must drop broad Raid Now update policy");
assert.match(p0HardeningMigration, /drop policy if exists "Users update own quest help posts"/, "P0 migration must drop broad Quest Help update policy");
assert.match(schema, /close_raid_now_post/, "schema must include close raid RPC");
assert.match(schema, /close_quest_help_post/, "schema must include close quest RPC");
assert.match(p0HardeningMigration, /allowed_mime_types = array\['image\/jpeg', 'image\/png', 'image\/webp'\]/, "avatars bucket must restrict MIME types");
assert.match(avatarStorage, /AVATAR_MAX_BYTES = 5 \* 1024 \* 1024/, "avatar upload helper must validate size");
assert.match(avatarStorage, /avatarPathForUser\(userId, extension\)/, "avatar upload helper must use canonical path");
assert.match(nextConfig, /Content-Security-Policy/, "production CSP must be enforced");
assert.match(nextConfig, /isProduction \? null : "'unsafe-eval'"/, "production CSP must remove unsafe-eval");
assert.match(rootLayout, /next\/font\/local/, "build must use local fonts");
assert.doesNotMatch(rootLayout, /next\/font\/google/, "build must not use Google fonts");
assert.match(gitignore, /^\.env\*$/m, ".env* must be ignored");
assert.match(gitignore, /^\.next$/m, ".next must be ignored");
assert.match(gitignore, /^node_modules$/m, "node_modules must be ignored");
assert.match(gitignore, /^\/test-results$/m, "test-results must be ignored");
assert.match(gitignore, /^\/playwright-report$/m, "playwright-report must be ignored");
assert.match(gitignore, /^\*.tsbuildinfo$/m, "tsbuildinfo must be ignored");
assert.match(packageJson, /"zip:clean"/, "package must include clean zip script");
assert.match(packageJson, /"check:artifact"/, "package must include artifact check script");

assert.doesNotMatch(schema, /\n  where reset_at < now\(\)/, "check_rate_limit must qualify reset_at (the bare name clashes with the OUT column and made every call fail)");
assert.match(schema, /stale\.reset_at < now\(\)/, "check_rate_limit cleanup must use the qualified column");
assert.match(v11Migration, /stale\.reset_at < now\(\)/, "v1.1 migration must ship the check_rate_limit fix");
assert.match(schema, /create trigger raid_now_posts_close_expired/, "expired Raid Now posts must be closed before inserts");
assert.match(schema, /create table public\.raid_now_responses/, "schema must include Raid Now responses");
assert.match(schema, /create or replace function public\.decide_post_response/, "schema must include the accept/decline RPC");
assert.match(schema, /create or replace function public\.delete_my_account/, "schema must include self-service account deletion");
assert.match(schema, /where c\.game_modes && me\.game_modes/, "swipe must only pair players that share a game mode");
assert.match(schema, /status = 'pending'\n  and match_id is null/, "responders must not be able to insert accepted responses");
assert.match(postResponsesAction, /checkPersistentRateLimit/, "post responses must be rate limited");
assert.match(postResponsesAction, /containsForbiddenTradeText/, "post responses must block RMT language");
assert.match(authCallback, /ignoreDuplicates: true/, "OAuth callback must not overwrite the Discord handle chosen in onboarding");
assert.doesNotMatch(authCallback, /from\("profiles"\)\.upsert/, "OAuth callback must not overwrite nicknames on every login");
assert.match(chatAction, /\.select\("id, match_id, sender_id, body, created_at"\)\s*\.single\(\)/, "sent messages must be returned so they show without Realtime");
assert.match(chatAction, /datetime\(\{ offset: true \}\)/, "older-message cursors must accept Postgres timestamps with offsets");

const v12Migration = read("supabase/migrations/20260926100000_v1_2_scale.sql");
assert.match(v12Migration, /recent as materialized/, "swipe candidates must be scored from a bounded pool");
assert.match(schema, /limit 4000/, "the swipe window must stay bounded regardless of player count");
assert.doesNotMatch(schema.slice(schema.indexOf("alter table public.profiles enable row level security;")), /[^(]select auth\.uid\(\)|(?<!\(select )auth\.uid\(\)(?=[^)]*\bon\b)/, "RLS policies must use (select auth.uid())");
assert.match(schema, /create trigger messages_after_insert/, "match summaries must be maintained by trigger");
assert.match(schema, /realtime\.broadcast_changes/, "chat must broadcast from the database");
assert.doesNotMatch(schema, /alter publication supabase_realtime add table public\.messages/, "messages must not go through Postgres Changes");
assert.match(schema, /create unlogged table public\.rate_limit_buckets/, "rate limit buckets must be unlogged");
assert.match(chatPanel, /private: true/, "chat must subscribe to a private Broadcast channel");
assert.doesNotMatch(chatPanel, /postgres_changes/, "chat must not use Postgres Changes");
assert.doesNotMatch(read("src/lib/supabase/queries.ts") + read("src/lib/supabase/middleware.ts"), /auth\.getUser\(\)/, "request paths must verify sessions with getClaims(), not an Auth server round trip");

console.log("Beta checks passed.");
