import type { Profile, ProfileTarkovStats } from "@/lib/constants";
import type { SessionUser } from "@/lib/supabase/session";

export const DEMO_USER_ID = "00000000-0000-4000-8000-000000000001";
export const DEMO_CANDIDATE_ID = "00000000-0000-4000-8000-000000000002";
export const DEMO_MATCH_PROFILE_ID = "00000000-0000-4000-8000-000000000003";
export const DEMO_MATCH_ID = "00000000-0000-4000-8000-000000000010";

export const demoUser: SessionUser = {
  id: DEMO_USER_ID,
  user_metadata: { full_name: "Operador Demo" },
};

export type DemoPerson = {
  profile: Profile;
  contact: { discord_username: string; discord_id: string };
  stats: ProfileTarkovStats | null;
  // Demo players that already liked you: liking them back creates a match.
  likesYou: boolean;
  replies: string[];
};

export const demoCurrentProfile: Profile = {
  id: DEMO_USER_ID,
  nickname: "Operador Demo",
  avatar_url: null,
  region: "EU",
  language: "ES",
  spoken_languages: ["ES", "EN"],
  approximate_level: 35,
  favorite_maps: ["Customs", "Woods"],
  play_styles: ["Quest focused", "Chill"],
  objectives: ["Misiones", "Aprender"],
  schedule: ["Noche", "Fines de semana"],
  game_modes: ["PvP"],
  bio: "Busco dúo estable para quests de early wipe y extracciones limpias.",
  onboarding_complete: true,
  last_active_at: null,
};

export const demoCurrentContact = { discord_username: "operador_demo", discord_id: "1234567890" };

export const demoCurrentStats: ProfileTarkovStats = {
  id: "00000000-0000-4000-8000-000000000020",
  user_id: DEMO_USER_ID,
  tarkov_profile_url: "https://tarkov.dev/players/regular/2421869",
  tarkov_player_id: "2421869",
  profile_mode: "regular",
  stats_json: { source: "manual" },
  level: 35,
  survival_rate: 52.5,
  kd: 3.1,
  raids: 180,
  hours: 430,
  pmc_kills: 190,
  last_synced_at: null,
  is_public: true,
};

function person(
  index: number,
  profile: Omit<Profile, "id" | "avatar_url" | "onboarding_complete">,
  options: { likesYou?: boolean; stats?: Omit<ProfileTarkovStats, "user_id" | "is_public" | "last_synced_at"> | null; replies?: string[] } = {},
): DemoPerson {
  const id = `00000000-0000-4000-8000-${String(100 + index).padStart(12, "0")}`;
  return {
    profile: { ...profile, id, avatar_url: null, onboarding_complete: true },
    contact: { discord_username: profile.nickname.toLowerCase(), discord_id: String(900000 + index) },
    stats: options.stats ? { ...options.stats, user_id: id, is_public: true, last_synced_at: null } : null,
    likesYou: options.likesYou ?? false,
    replies: options.replies ?? ["Perfecto, te agrego en Discord y entramos.", "Voy con comms, dime mapa y hora."],
  };
}

export const demoCandidateSherpa: DemoPerson = {
  profile: {
    id: DEMO_CANDIDATE_ID,
    nickname: "CustomsSherpa",
    avatar_url: null,
    region: "EU",
    language: "EN",
    spoken_languages: ["EN", "ES", "IT"],
    approximate_level: 42,
    favorite_maps: ["Customs", "Ground Zero"],
    play_styles: ["Sherpa", "Quest focused"],
    objectives: ["Misiones", "Aprender"],
    schedule: ["Noche"],
    game_modes: ["PvP"],
    bio: "Sherpa chill para quests, extracciones limpias y buen comms.",
    onboarding_complete: true,
    compatibility_score: 100,
    compatibility_reasons: [
      "compat.language.speaksYourLanguage",
      "compat.region.same:region=EU",
      "compat.objective.sharedQuests",
      "compat.map.shared:map=Customs",
      "compat.schedule.compatible",
    ],
    compatibility_warnings: [],
    shared_languages: ["ES"],
    shared_maps: ["Customs"],
    shared_objectives: ["Misiones", "Aprender"],
    shared_styles: ["Quest focused"],
  },
  contact: { discord_username: "customssherpa", discord_id: "5555555555" },
  stats: {
    user_id: DEMO_CANDIDATE_ID,
    level: 42,
    survival_rate: 58.4,
    kd: 4.2,
    raids: 320,
    hours: 840,
    pmc_kills: 410,
    last_synced_at: null,
    is_public: true,
  },
  likesYou: true,
  replies: ["¡Buenas! Esta noche hago Dorms en Customs, ¿te vienes?", "Llevo llave de marked, entramos a las 22:00."],
};

export const demoMatchedPerson: DemoPerson = {
  profile: {
    id: DEMO_MATCH_PROFILE_ID,
    nickname: "NightOperator",
    avatar_url: null,
    region: "EU",
    language: "ES",
    spoken_languages: ["ES", "EN"],
    approximate_level: 39,
    favorite_maps: ["Woods", "Customs"],
    play_styles: ["Chill", "Sniper"],
    objectives: ["Misiones", "Scav runs"],
    schedule: ["Noche"],
    game_modes: ["PvP"],
    bio: "Jugador nocturno para dúo estable y quests.",
    onboarding_complete: true,
    compatibility_score: 92,
    compatibility_reasons: ["compat.language.speaksYourLanguage", "compat.region.same:region=EU", "compat.schedule.compatible"],
    compatibility_warnings: [],
    shared_languages: ["ES", "EN"],
    shared_maps: ["Woods", "Customs"],
    shared_objectives: ["Misiones"],
    shared_styles: ["Chill"],
  },
  contact: { discord_username: "nightoperator", discord_id: "9999999999" },
  stats: null,
  likesYou: true,
  replies: ["Hecho. Te espero en el lobby a las 22:00.", "Llevo meds de sobra, tú trae el comms."],
};

export const demoPeople: DemoPerson[] = [
  demoCandidateSherpa,
  person(1, {
    nickname: "KiloRaptor",
    region: "EU",
    language: "ES",
    spoken_languages: ["ES", "EN"],
    approximate_level: 42,
    favorite_maps: ["Customs", "Reserve"],
    play_styles: ["Quest focused", "Chill"],
    objectives: ["Misiones", "Boss hunting"],
    schedule: ["Noche", "Fines de semana"],
    game_modes: ["PvP"],
    bio: "PMC metódico, buen comms, priorizo quests y extracciones limpias.",
    compatibility_score: 94,
    compatibility_reasons: ["compat.language.speaksYourLanguage", "compat.region.same:region=EU", "compat.objective.sharedQuests", "compat.map.shared:map=Customs"],
    compatibility_warnings: [],
    shared_languages: ["ES", "EN"],
    shared_maps: ["Customs"],
    shared_objectives: ["Misiones"],
    shared_styles: ["Quest focused", "Chill"],
  }, { likesYou: true, stats: { level: 44, survival_rate: 61.2, kd: 5.1, raids: 410, hours: 990, pmc_kills: 530 } }),
  person(2, {
    nickname: "NightCourier",
    region: "EU",
    language: "EN",
    spoken_languages: ["EN", "ES"],
    approximate_level: 31,
    favorite_maps: ["Streets of Tarkov", "Interchange"],
    play_styles: ["Loot goblin", "Rat"],
    objectives: ["Loot runs", "Farmear dinero"],
    schedule: ["Madrugada"],
    game_modes: ["PvP"],
    bio: "Rutas de alto valor con poco ruido. Conoce alijos y evita peleas innecesarias.",
    compatibility_score: 64,
    compatibility_reasons: ["compat.language.sharedLanguage", "compat.region.same:region=EU"],
    compatibility_warnings: ["compat.warning.poorSchedule"],
    shared_languages: ["ES", "EN"],
  }),
  person(3, {
    nickname: "ShorelineDoc",
    region: "EU",
    language: "ES",
    spoken_languages: ["ES", "FR"],
    approximate_level: 18,
    favorite_maps: ["Shoreline", "Woods"],
    play_styles: ["Sherpa", "New player"],
    objectives: ["Aprender", "Misiones"],
    schedule: ["Noche"],
    game_modes: ["PvP", "PvE"],
    bio: "Ayudo con rutas, extracts y quests tempranas. Cero flame.",
    compatibility_score: 88,
    compatibility_reasons: ["compat.language.speaksYourLanguage", "compat.region.same:region=EU", "compat.schedule.compatible", "compat.map.shared:map=Woods"],
    compatibility_warnings: [],
    shared_languages: ["ES"],
    shared_maps: ["Woods"],
    shared_objectives: ["Aprender", "Misiones"],
  }, { likesYou: true }),
  person(4, {
    nickname: "LabsOrNothing",
    region: "NA",
    language: "EN",
    spoken_languages: ["EN", "ES"],
    approximate_level: 58,
    favorite_maps: ["The Lab", "Factory"],
    play_styles: ["Tryhard", "PvP"],
    objectives: ["Labs", "PvP"],
    schedule: ["Noche"],
    game_modes: ["PvP"],
    bio: "Avisos rápidos, peleas rápidas y reset sin drama. Busco dúo con confianza.",
    compatibility_score: 52,
    compatibility_reasons: ["compat.language.sharedLanguage", "compat.schedule.compatible"],
    compatibility_warnings: ["compat.warning.distantRegion", "compat.warning.differentPace"],
    shared_languages: ["ES", "EN"],
  }, { stats: { level: 61, survival_rate: 71.5, kd: 9.8, raids: 890, hours: 2600, pmc_kills: 3100 } }),
  person(5, {
    nickname: "WoodsGhost",
    region: "LATAM",
    language: "PT",
    spoken_languages: ["PT", "ES", "EN"],
    approximate_level: 27,
    favorite_maps: ["Woods", "Lighthouse"],
    play_styles: ["Sniper", "Chill"],
    objectives: ["Scav runs", "Loot runs"],
    schedule: ["Fines de semana"],
    game_modes: ["PvP"],
    bio: "Cobertura a larga distancia, rotaciones lentas y extracciones limpias.",
    compatibility_score: 71,
    compatibility_reasons: ["compat.language.speaksYourLanguage", "compat.region.compatible", "compat.schedule.sharedWeekends", "compat.map.shared:map=Woods"],
    compatibility_warnings: [],
    shared_languages: ["ES", "EN"],
    shared_maps: ["Woods"],
    shared_styles: ["Chill"],
  }),
  person(6, {
    nickname: "DormsKeeper",
    region: "EU",
    language: "FR",
    spoken_languages: ["FR", "EN"],
    approximate_level: 46,
    favorite_maps: ["Customs", "Ground Zero"],
    play_styles: ["Sherpa", "Quest focused"],
    objectives: ["Misiones", "Aprender"],
    schedule: ["Tarde", "Noche"],
    game_modes: ["PvP"],
    bio: "Guía paciente para rutas de early wipe y quests de dorms.",
    compatibility_score: 81,
    compatibility_reasons: ["compat.language.sharedEnglish", "compat.region.same:region=EU", "compat.objective.sharedQuests", "compat.map.shared:map=Customs"],
    compatibility_warnings: [],
    shared_languages: ["EN"],
    shared_maps: ["Customs"],
    shared_objectives: ["Misiones", "Aprender"],
    shared_styles: ["Quest focused"],
  }),
  person(7, {
    nickname: "ReserveRat",
    region: "EU",
    language: "DE",
    spoken_languages: ["DE", "EN"],
    approximate_level: 39,
    favorite_maps: ["Reserve", "Factory"],
    play_styles: ["Rat", "Loot goblin"],
    objectives: ["Farmear dinero", "Scav runs"],
    schedule: ["Madrugada"],
    game_modes: ["PvP"],
    bio: "Rutas subterráneas, disciplina de loot y más supervivencia que ego.",
    compatibility_score: 48,
    compatibility_reasons: ["compat.language.sharedEnglish", "compat.region.same:region=EU"],
    compatibility_warnings: ["compat.warning.poorSchedule"],
    shared_languages: ["EN"],
  }),
  person(8, {
    nickname: "StreetsRunner",
    region: "NA",
    language: "ES",
    spoken_languages: ["ES", "EN"],
    approximate_level: 34,
    favorite_maps: ["Streets of Tarkov", "Interchange"],
    play_styles: ["PvP", "Quest focused"],
    objectives: ["PvP", "Misiones"],
    schedule: ["Noche"],
    game_modes: ["PvP"],
    bio: "Agresivo pero no imprudente. Canta jugadas y rota rápido.",
    compatibility_score: 67,
    compatibility_reasons: ["compat.language.speaksYourLanguage", "compat.schedule.compatible", "compat.style.similar"],
    compatibility_warnings: ["compat.warning.distantRegion"],
    shared_languages: ["ES", "EN"],
    shared_objectives: ["Misiones"],
    shared_styles: ["Quest focused"],
  }),
  person(9, {
    nickname: "GroundZeroDad",
    region: "EU",
    language: "ES",
    spoken_languages: ["ES", "IT"],
    approximate_level: 12,
    favorite_maps: ["Ground Zero", "Customs"],
    play_styles: ["New player", "Chill"],
    objectives: ["Aprender", "Misiones"],
    schedule: ["Fines de semana"],
    game_modes: ["PvP", "PvE"],
    bio: "Nuevo wipe, ganas de aprender y jugar tranquilo por las noches.",
    compatibility_score: 83,
    compatibility_reasons: ["compat.language.speaksYourLanguage", "compat.region.same:region=EU", "compat.schedule.sharedWeekends", "compat.map.shared:map=Customs"],
    compatibility_warnings: [],
    shared_languages: ["ES"],
    shared_maps: ["Customs"],
    shared_objectives: ["Aprender", "Misiones"],
    shared_styles: ["Chill"],
  }, { likesYou: true }),
];

export const demoTasks = [
  {
    id: "e2e-task-extortionist",
    name: "The Extortionist",
    normalizedName: "the-extortionist",
    trader: { name: "Skier" },
    map: { name: "Customs" },
    wikiLink: "https://escapefromtarkov.fandom.com/wiki/The_Extortionist",
    minPlayerLevel: 7,
    taskRequirements: [{ task: { id: "e2e-task-supplier", name: "Supplier" } }],
    objectives: [
      {
        id: "e2e-objective-1",
        type: "findItem",
        description: "Obtain the valuable cargo on Customs",
        optional: false,
        maps: [{ id: "customs", name: "Customs" }],
      },
      {
        id: "e2e-objective-2",
        type: "extract",
        description: "Survive and extract from Customs",
        optional: false,
        maps: [{ id: "customs", name: "Customs" }],
      },
    ],
  },
  {
    id: "e2e-task-multi-map",
    name: "Signal Sweep",
    normalizedName: "signal-sweep",
    trader: { name: "Mechanic" },
    map: null,
    wikiLink: null,
    minPlayerLevel: 12,
    taskRequirements: [],
    objectives: [
      {
        id: "e2e-objective-3",
        type: "mark",
        description: "Mark signal sources on Woods or Customs",
        optional: false,
        maps: [
          { id: "woods", name: "Woods" },
          { id: "customs", name: "Customs" },
        ],
      },
    ],
  },
];
